/**
 * ---------------------------------------------------------
 * Folder: app/
 * Location: client/src/app/
 * ---------------------------------------------------------
 *
 * Folder Purpose:
 *   The `app` directory contains the global configuration elements that bind
 *   the entire application together, such as the Redux store configuration.
 *
 * ---------------------------------------------------------
 * File: store.js
 * Location: client/src/app/store.js
 * ---------------------------------------------------------
 *
 * Purpose:
 *   Maintains the global client-side application state for authentication.
 *   This ensures that the login token and current user's profile details are
 *   accessible to any component in the application.
 *
 * Responsibilities:
 * - Bootstraps the Redux store using Redux Toolkit's `configureStore`.
 * - Creates the `auth` slice using `createSlice` to manage authentication state.
 * - Synchronizes token changes to localStorage via API helpers.
 * - Exports Redux action creators (`signedIn`, `signedOut`) to trigger login/logout flows.
 *
 * State:
 * - token: The JWT (JSON Web Token) string. Initialized by checking localStorage.
 * - user: The authenticated user's profile object (ID, name, email). Defaults to null.
 *
 * Example Flow:
 * User logs in successfully (AuthPanel)
 * ↓
 * AuthPanel calls dispatch(signedIn({ token, user }))
 * ↓
 * signedIn reducer executes
 * ↓
 * State is updated with token and user info
 * ↓
 * setToken(token) saves JWT to localStorage
 * ↓
 * Redux selectors (useSelector) fire re-renders in subscribing components (like App.jsx)
 *
 * Related Files:
 * - client/src/lib/api.js (Local storage token getters/setters)
 * - client/src/components/AuthPanel.jsx (Form that dispatches signedIn)
 * - client/src/App.jsx (Reads token/user to render screen options)
 */

import { configureStore, createSlice } from "@reduxjs/toolkit";
import { getToken, setToken } from "../lib/api";

/**
 * Initial state structure for the Auth slice.
 * Loads the token from localStorage on boot to maintain session persistence.
 *
 * Why useState is NOT used here:
 *   This state needs to be accessed globally by many non-hierarchical components.
 *   Using useState at the root would require extensive "prop drilling", which is
 *   hard to maintain. Redux provides a global store container that components
 *   can tap into directly.
 */
const initialState = { token: getToken(), user: null };

/**
 * =============================================================================
 * REACT CONCEPT: Redux Toolkit (RTK) Slice
 * =============================================================================
 * Definition:
 *   A collection of Redux reducer logic and actions for a single feature,
 *   defined in one place using `createSlice`.
 *
 * Why it is used here:
 *   Traditional Redux requires writing action types, action creators, and reducers
 *   in separate files with massive switch-statements. `createSlice` autogenerates
 *   action creators and action types based on the reducer names.
 *
 * Redux Toolkit State Mutations (Immer):
 *   Notice that we are directly assigning values to state fields (e.g. `state.token = ...`).
 *   Normally, Redux state must be updated immutably (returning a new state object).
 *   However, RTK uses `Immer` under the hood, which intercepts these mutations and
 *   safely generates an immutable update on our behalf.
 *
 * References:
 * - https://redux-toolkit.js.org/api/createSlice
 * - https://immerjs.github.io/immer/
 */
const authSlice = createSlice({
  name: "auth",
  initialState,
  reducers: {
    /**
     * Updates authentication state upon successful sign-in or signup.
     * Synchronizes the JWT token with localStorage.
     *
     * Inputs:
     * - state: The current draft state of the auth slice.
     * - action: Redux action containing payload: { token: string, user: object }
     */
    signedIn(state, action) {
      state.token = action.payload.token;
      state.user = action.payload.user;
      // Side Effect: Keep localStorage updated so sessions survive page reloads
      setToken(action.payload.token);
    },
    /**
     * Clears authentication credentials, effectively logging the user out.
     */
    signedOut(state) {
      state.token = null;
      state.user = null;
      // Side Effect: Clear the token from localStorage to end session
      setToken(null);
    }
  }
});

// Action creators generated by createSlice
export const { signedIn, signedOut } = authSlice.actions;

/**
 * =============================================================================
 * REACT CONCEPT: Redux Store Configuration
 * =============================================================================
 * Definition:
 *   The Redux store is the single source of truth containing the global application state.
 *   `configureStore` simplifies store creation by setting up middleware (like Redux DevTools)
 *   and combining slice reducers automatically.
 *
 * References:
 * - https://redux-toolkit.js.org/api/configureStore
 * - https://react-redux.js.org/introduction/getting-started
 */
export const store = configureStore({ reducer: { auth: authSlice.reducer } });
